### PR TITLE
Add support for gnome 44 and bump version to 12 

### PR DESCRIPTION
**Pull request by sh4r10**
change metadata.json to include gnome 44 and change the version number to 12.

### CODE REVIEW

**Comment by velitasali** [comment]
Hi @sh4r10! 

Thanks for this. Looks like #36 isn't fixed by this. Maybe we can merge after removing the "Closes #..." and the reference from the commit message?

**Comment by sh4r10** [comment]
Hey @velitasali, I have made the changes you wanted. I didn't realize there was more to the issue than just the version update. I would understand if you want to hold off on merging until you have further investigated the issues. Thanks for getting back to me.

**Comment by velitasali** [comment]
@sh4r10, your changes are still valid. We can merge it now. I think the reference in the commit message can stay too. I am goint to update the PR message so that it doesn't close the linked it issue.

Edit:

You seem to have already done that. Thank you!

**Comment by Hole-code** [comment]
changing metadata.json didn't solve the problem. The extension starts but does not work. Headlines remain

**Comment by Hole-code** [comment]
fedora 38 gnome 44

**Pull request merged**
